
# Author: sudo-iris

"ui.background" = { }
"ui.menu" = { fg = "text", bg = "overlay" }
"ui.menu.selected" = { fg = "iris", bg = "surface" }
"ui.linenr" = {fg = "subtle" }
"ui.liner.selected" = "highlightOverlay"
"ui.selection" = { bg = "highlightMed" }
"comment" = "muted"
"ui.statusline" = {fg = "text", bg = "base" }
"ui.statusline.insert" = {fg = "base", bg = "ice", modifiers = ["bold"]}
"ui.statusline.normal" = {fg = "base", bg = "pink", modifiers = ["bold"]}
"ui.statusline.select" = {fg = "base", bg = "iris", modifiers = ["bold"]}
"ui.statusline.inactive" = { fg = "subtle", bg = "surface" }
"ui.cursor" = { fg = "pink", modifiers = ["reversed"] }
"ui.highlight" = { bg = "highlightLow"}
"ui.text" = { fg = "text" }
"ui.text.focus" = { fg = "ice", modifiers = ["bold"]}
"ui.text.info" = {fg = "sea", modifiers = ["bold"]}
"ui.virtual.whitespace" = "text"
"operator" = "pink"
"variable" = "text"
"constant.numeric" = "iris"
"constant" = "gold"
"attributes" = "gold" 
"type" = "sea"
"ui.cursor.match" = { fg = "gold", modifiers = ["underlined"] }
"string" = "gold"
"property" = "ice"
"constant.character.escape" = "subtle"
"function" = "kiss"
"function.builtin" = "kiss"
"function.method" = "sea"
"constructor" = "gold"
"special" = "gold"
"keyword" = "ice"
"label" = "iris"
"namespace" = "sea"
"ui.popup" = { bg = "surface" }
"ui.popup.info" = { bg = "surface" }
"ui.window" = { bg = "base" }
"ui.help" = {bg = "overlay", fg = "sea" }
"text" = "text"
"diff.plus" = "sea"
"diff.delta" = "pink"
"diff.minus" = "pink"

"info" = "gold"
"hint" = "gold"
"debug" = "kiss"
"diagnostic" = "rose"
"error" = "pink"

"markup.heading.marker" = "subtle"
"markup.heading.1" = { fg = "pink", modifiers = ["bold"] }
"markup.heading.2" = { fg = "gold", modifiers = ["bold"] }
"markup.heading.3" = { fg = "pink", modifiers = ["bold"] }
"markup.heading.4" = { fg = "sea", modifiers = ["bold"] }
"markup.heading.5" = { fg = "ice", modifiers = ["bold"] }
"markup.heading.6" = { fg = "iris", modifiers = ["bold"] }
"markup.list" = { fg = "kiss" }
"markup.bold" = { fg = "gold", modifiers = ["bold"] }
"markup.italic" = { fg = "iris", modifiers = ["italic"] }
"markup.link.url" = { fg = "sea", modifiers = ["underlined"]}
"markup.link.text" = { fg = "ice" }
"markup.quote" = { fg = "kiss" }
"markup.raw" = { fg = "ice" }

[palette]
backgr 	= "#29030855"
base 	= "#191724"
surface = "#1f1d2e"
overlay = "#26233a"
inactive= "#5b5579"
subtle 	= "#8a82b4"
muted 	= "#6e6a86"
text 	= "#ffdbf2"
kiss 	= "#e43e6d"
gold 	= "#fcfc7b" 
pink 	= "#ffbace"
sea 	= "#2593be"
ice	= "#00fafa"
iris 	= "#cfaaff"
highlightLow 	  = "#696876"
highlightMed 	  = "#646176"
highlightHigh	  = "#76738b"
ihighlightInactive = "#211f2d"
highlightOverlay  = "#3a384a"
